### PR TITLE
Support multiple value while identify image.

### PR DESCRIPTION
**Pull request by emaniacs**
When metadata has multiple value like keywords parser(./lib/getters.js)
just take the last because parser override the previous value.
Instead of override this commit cast it to array.

### CODE REVIEW

**Comment by aheckmann** [comment]
Seems like this makes sense. Could you please add a test to show this working as intended?

**Comment by emaniacs** [comment]
I created the test.

**Comment by emaniacs** [comment]
This is the issue #508

**Comment by aheckmann** [comment]
Thanks!

**Pull request merged**
