### PR TITLE
Fix global leak in compare.js

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by papandreou** [comment]
@aheckmann, ping?

**Comment by oliviertassinari** [comment]
👍

**Comment by papandreou** [comment]
@danez, ping?

**Comment by papandreou** [comment]
@danez, is there anything blocking this from being merged? It's such a trivial thing, and it's been two years now :)

**Comment by papandreou** [comment]
I'll close this so I don't have to look at it in my list of open PRs. Seems unlikely that it'll ever get merged at this point.

**Pull request closed without merging**
